Copied over implementation from initial project
broadway/event-store-mongodb pull request #1
Opened 2017-02-22 14:30 UTC by robinvdvleuten

I've copied over the original class from the initial project. Just to take a peek at for now. There are still some small things to do before it can be merged;

- [x]  copy class from initial project
- [ ] remove reference to `App\MongoDB\Client`
- [ ] test all the things

2017-02-22 16:43 UTC, othillo requested changes

2017-02-22 16:43 UTC, othillo commented on composer.json
> +            "dev-master": "1.0.x-dev"
maybe start with 0.2.x-dev first?

2017-02-22 16:43 UTC, othillo commented on src/MongoDBEventStore.php
> +        if (empty($messages)) {
can you move this to line 58 using if 0 === $cursor->count() ?

2017-02-22 16:50 UTC, othillo approved these changes

2017-08-23 14:04 UTC, merged

2017-08-23 14:04 UTC, wjzijderveld commented
Thanks @robinvdvleuten @wgorczyca and @othillo !

2017-08-23 16:06 UTC, robinvdvleuten commented
Thanks for all the effort the last days guys! Too bad I haven't found the time to finish the PR.