Rewritten mongo store with tests
broadway/event-store-mongodb pull request #3
Opened 2017-08-07 08:30 UTC by wgorczyca

Rewritten mongo store with tests

2017-08-14 07:42 UTC, othillo commented
I suggest requiring only ext-mongodb (and not ext-mongo).

2017-08-15 14:22 UTC, wgorczyca commented
Removed doctrine/mongodb from composer.json, added ext-mongodb
Renamed namespaces from Mongo to MongoDB
MongoDBEventStore now takes collection as argument instead of database and collection name

2017-08-19 13:48 UTC, wjzijderveld requested changes
Some small things I noticed. After that I think we can merge this and let Travis have a go at it :-)

2017-08-19 13:48 UTC, wjzijderveld commented on .travis.yml
> +  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || return 0; fi
I think we need the some for PHP7 with mongodb.so

2017-08-19 13:48 UTC, wjzijderveld commented on .travis.yml
> +  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then travis_retry composer require "alcaeus/mongo-php-adapter=^1.0.0" --ignore-platform-reqs; fi
Why do we need `--ignore-platform-reqs` here?

2017-08-19 13:48 UTC, wjzijderveld commented on src/MongoDBEventStore.php
> +            ],['sort' => ['payhead' => MongoCollection::ASCENDING]]);
typo: `playhead`

2017-08-19 13:48 UTC, wjzijderveld commented on src/MongoDBEventStore.php
> +        $events = [];
nit: it are domain messages, not direct events

2017-08-19 13:48 UTC, wjzijderveld commented on src/MongoDBEventStore.php
> +            ],['sort' => ['payhead' => MongoCollection::ASCENDING]]);
typo

2017-08-19 13:48 UTC, wjzijderveld commented on src/MongoDBEventStore.php
> +            throw new DuplicatePlayheadException($eventStream, $exception);
Is there a more specific errorCode we can check before throwing this exception?

2017-08-19 18:19 UTC, othillo commented on .travis.yml
> +  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then travis_retry composer require "alcaeus/mongo-php-adapter=^1.0.0" --ignore-platform-reqs; fi
it is recommended: https://github.com/alcaeus/mongo-php-adapter#installation

2017-08-19 18:22 UTC, othillo commented on .travis.yml
> +  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then travis_retry composer require "alcaeus/mongo-php-adapter=^1.0.0" --ignore-platform-reqs; fi
but it can be removed because this PR only uses ext-mongodb (the new one :))

2017-08-19 18:35 UTC, othillo requested changes

2017-08-19 18:35 UTC, othillo commented on README.md
> +> Note: to use MongoDB on PHP7 you will also need to install alcaeus/mongo-php-adapter
this can be removed

2017-08-19 18:35 UTC, othillo commented on composer.json
> +    "suggest": {
this can be removed

2017-08-19 18:35 UTC, othillo commented on phpunit.xml.dist
> +            <group>mongo</group>
nit: mongodb

2017-08-19 18:35 UTC, othillo commented on src/MongoDBEventStore.php
> +
nit: whitespace

2017-08-19 18:36 UTC, othillo commented on .gitignore
> +.DS_Store
I prefer you add these to your personal global .gitigore file

2017-08-19 18:38 UTC, othillo commented on .travis.yml
> +    - php: 5.5
I suggest not testing PHP 5.5 anymore.

2017-08-19 18:57 UTC, othillo commented
@wgorczyca thanks for your efforts so far. I think we're really close to merging this!

2017-08-22 18:00 UTC, wgorczyca commented on src/MongoDBEventStore.php
> +            throw new DuplicatePlayheadException($eventStream, $exception);
Unfortunately, I think there is no more specific errorCode 😢

2017-08-22 18:00 UTC, wgorczyca commented
@othillo @wjzijderveld updated travis config and fixed typos etc. ;)

2017-08-23 09:31 UTC, othillo approved these changes

2017-08-23 09:32 UTC, othillo commented
LGTM!

2017-08-23 09:57 UTC, wjzijderveld commented on src/MongoDBEventStore.php
> +            throw new DuplicatePlayheadException($eventStream, $exception);
What about error code 11000? https://docs.mongodb.com/manual/core/index-unique/#unique-index-and-missing-field

2017-08-23 10:10 UTC, wgorczyca commented on src/MongoDBEventStore.php
> +            throw new DuplicatePlayheadException($eventStream, $exception);
Thanks, take a look now ;)

2017-08-23 12:22 UTC, merged

2017-08-23 12:23 UTC, wjzijderveld commented
Thanks @wgorczyca !